### ISSUE TITLE
PacmanVision Pics and Media

### ISSUE THREAD

**Issue by Tabjones** [Tabjones/pacman_vision#1]
![intro](https://cloud.githubusercontent.com/assets/1950251/12723299/22f2d844-c909-11e5-9621-142a1d49dcd4.png)

![estimator](https://cloud.githubusercontent.com/assets/1950251/12723307/275b07d0-c909-11e5-9f82-cdb524847532.png)

![tracker](https://cloud.githubusercontent.com/assets/1950251/12723311/2b50ad90-c909-11e5-9040-233b1cf22a83.gif)

![listener](https://cloud.githubusercontent.com/assets/1950251/12723314/2e92225e-c909-11e5-83b5-af4182cba8c1.png)

**Comment by Tabjones** [comment]
This is just a fake issue to upload pics on github without actually putting them into the version control system.

**Comment by carlosjoserg** [comment]
haha, nice pics! On Wednesday, first thing I'll do is to update the pacman vision module to have this cool qt things ;)

**Comment by Tabjones** [comment]
I'm updating it myself: gonna do a release on master, then that can go directly into DR54!

**Comment by carlosjoserg** [comment]
:+1:

**Comment by Tabjones** [comment]
![intro2](https://cloud.githubusercontent.com/assets/1950251/12747148/958500dc-c9a2-11e5-8d2b-f8e094e90004.png)

**Comment by carlosjoserg** [comment]
Is that Need for Speed?

**Comment by Tabjones** [comment]
No, it's just that github doesnt let you drag-drop pics into readmes and wikis, you need the url of the pic... So i'm fooling it with this fake issue ! Since i'm lazy and i dont want to upload the pics somewhere else

**Comment by carlosjoserg** [comment]
haha, I'm just kidding about the qt interface, looks very pro...

**Comment by Tabjones** [comment]
There's the qtcreatror projects for the gui, in case you want to try it/them (without building the whole pacman vision package)

**Comment by Tabjones** [comment]
![sensor](https://cloud.githubusercontent.com/assets/1950251/12750569/4fd221c6-c9b8-11e5-9686-90beedb1120f.png)
