### ISSUE TITLE
I can't push to the github mirror

### ISSUE THREAD

**Issue by carlosjoserg** [Tabjones/pacman_vision#2]
I updated pacman-DR54 with the github mirror, and now I lost write access...

Can I? :pray:  

I only need to update the DR54.yaml param, but if you prefer to keep it like this, I'll educated-ly follow the fork&PR road...

**Comment by carlosjoserg** [comment]
danks!

**Comment by Tabjones** [comment]
I made you a collaborator, i've no idea how to make you admin... you should have push access anyway
